### ISSUE TITLE
schtasks_scheduling_job_on_remote_system.yml observables correction

### ISSUE THREAD

**Issue by 7h3sil3nce** [splunk/security_content#2203]
[https://github.com/splunk/security_content/blob/develop/detections/endpoint/schtasks_scheduling_job_on_remote_system.yml](url)
name: Schtasks scheduling job on remote system
id: 1297fb80-f42a-4b4a-9c8a-88c066237cf6

Incorrect fields are presented in the risk adaptive response, because of the macro stripping the DMA field value "Process".  These fields are not present in the results, so the search does not create a risk event upon detection.

![Screen Shot 2022-05-16 at 8 19 26 PM (1)](https://user-images.githubusercontent.com/22779462/169063592-e2677560-b899-4690-968d-140377af4f69.png)
![Screen Shot 2022-05-16 at 8 19 02 PM (1)](https://user-images.githubusercontent.com/22779462/169063615-21dbfb4c-ee40-4a47-a3a6-f41784598466.png)

Current
```
observable:
  - name: Processes.dest
    type: Hostname
    role:
    - Victim
  - name: Processes.user
    type: User
    role:
    - Victim
```

Suggested change

```
observable:
  - name: dest
    type: Hostname
    role:
    - Victim
  - name: user
    type: User
    role:
    - Victim
```
