### ISSUE TITLE
macros.j2 not compatible with macros with two or more arguments

### ISSUE THREAD

**Issue by andsovik** [splunk/security_content#2492]
### **Description**
If you create a macro with two or more arguments in the macros folder, it will not compile correctly.
The reason for this is due to the jinja definition in _macros.j2_. 

#### **How to recreate:**
Paste the following content in a file under security_content/macros/test.yml
```yml
arguments:
- foo
- bar
definition: a=$foo$ b=$bar$
description: just for testing
name: test_macro
```

If this is compiled, you will end up with the following macros.conf under the dist folder:
```yml
[test_macro(2)]
args = foo,
bar
definition: a=$foo$ b=$bar$
description: just for testing
```

To fix this you need to change the _macros.j2_ file with the following code:
```j2
{% for macro in objects %}
[{{ macro.name }}{% if macro.arguments is not none %}({{ macro.arguments|length }}){% endif %}]
{% if macro.arguments is not none %}
args = {% for arg in macro.arguments -%}{{ arg }}{{ ", " if not loop.last }}{% endfor %}

{% endif %}
{% if macro.definition is not none %}
definition = {{ macro.definition }}
{% else %}
definition =
{% endif %}
description = {{ macro.description }}

{% endfor %}
```
Changes made above can be seen at the end of the "macro.arguments -%" where I added a dash. And also moving the _endfor_ up one line, and also adding a new line in between the _endfor_ and the _endif_.

This will result in the _macros.conf_ being compiled correctly like this:
```yml
[test_macro(2)]
args = foo, bar
definition: a=$foo$ b=$bar$
description: just for testing
```

#### **Version**
Latest: v3.55.0
